interface StatesByCity {
  [key: string]: string[]; // Agregar una firma de índice para permitir el acceso por string
}

export const PROVINCE_WITH_CANTONS: StatesByCity = {
  "San José": [
    "Acosta",
    "Alajuelita",
    "Aserrí",
    "Curridabat",
    "Desamparados",
    "Dota",
    "Escazú",
    "Goicoechea",
    "León Cortés Castro",
    "Montes de Oca",
    "Mora",
    "Moravia",
    "Pérez Zeledón",
    "Puriscal",
    "San José",
    "Santa Ana",
    "Tarrazú",
    "Tibás",
    "Turrubares",
    "Vázquez de Coronado",
  ],
  Limon: ["Guácimo", "Limón", "Matina", "Pococí", "Siquirres", "Talamanca"],
  Puntarenas: [
    "Buenos Aires",
    "Corredores",
    "Coto Brus",
    "Esparza",
    "Garabito",
    "Golfito",
    "Montes de Oro",
    "Osa",
    "Parrita",
    "Puntarenas",
    "Quepos",
  ],
  Heredia: [
    "Barva",
    "Belén",
    "Flores",
    "Heredia",
    "San Isidro",
    "San Pablo",
    "San Rafael",
    "Santa Bárbara",
    "Santo Domingo",
  ],
  Alajuela: [
    "Alajuela",
    "Atenas",
    "Grecia",
    "Guatuso",
    "Los Chiles",
    "Naranjo",
    "Orotina",
    "Palmares",
    "Poás",
    "Río Cuarto",
    "San Carlos",
    "San Mateo",
    "San Ramón",
    "Upala",
    "Valverde Vega",
    "Zarcero",
  ],
  Cartago: ["Alvarado", "Cartago", "El Guarco", "Jiménez", "La Unión", "Oreamuno", "Paraíso", "Turrialba"],
  Guanacaste: [
    "Abangares",
    "Bagaces",
    "Carrillo",
    "Cañas",
    "Hojancha",
    "La Cruz",
    "Liberia",
    "Nandayure",
    "Nicoya",
    "Santa Cruz",
    "Tilarán",
  ],
};

export const PROVINCES = Object.keys(PROVINCE_WITH_CANTONS);

export const DISTRICTS_BY_CANTON: StatesByCity = {
  Acosta: ["San Ignacio", "Guaitil", "Palmichal", "Cangrejal", "Sabanillas"],
  Alajuelita: ["Alajuelita", "San Josecito", "San Antonio", "Concepción", "San Felipe"],
  Aserrí: ["Aserrí", "Tarbaca", "Vuelta de Jorco", "San Gabriel", "Legua"],
  Atenas: ["Atenas", "Jesús", "Mercedes", "San Isidro", "Concepción"],
  "Buenos Aires": ["Buenos Aires", "Volcán", "Potrero Grande", "Boruca", "Pilas"],
  Cañas: ["Cañas", "Palmira", "San Miguel", "Bebedero", "Porozal"],
  Carrillo: ["Filadelfia", "Palmira", "Sardinal", "Belén", "Santa Rosa"],
  Corredores: ["Corredor", "La Cuesta", "Paso Canoas", "Laurel", "Gutiérrez Brown"],
  "Coto Brus": ["San Vito", "Sabalito", "Aguabuena", "Limoncito", "Pittier"],
  Curridabat: ["Curridabat", "Granadilla", "Sánchez", "Tirrases", "Tres Ríos"],
  Desamparados: ["Desamparados", "San Miguel", "San Juan de Dios", "San Rafael Arriba", "San Antonio"],
  Dota: ["Santa María", "Jardín", "Copey"],
  "El Guarco": ["El Tejar", "San Isidro", "Tobosi", "Patio de Agua"],
  Escazú: ["Escazú", "San Antonio", "San Rafael"],
  Esparza: ["Espíritu Santo", "San Juan Grande", "Macacona", "San Rafael", "San Jerónimo"],
  Flores: ["San Joaquín", "Barrantes", "Llorente"],
  Garabito: ["Jacó", "Tárcoles"],
  Goicoechea: ["Guadalupe", "San Francisco", "Calle Blancos", "Mata de Plátano", "Ipís"],
  Golfito: ["Golfito", "Puerto Jiménez", "Guaycará", "Pavón", "La Concepción"],
  Grecia: ["Grecia", "San Isidro", "San José", "San Roque", "Tacares"],
  Guácimo: ["Guácimo", "Mercedes", "Pocora", "Río Jiménez", "Duacarí"],
  Guatuso: ["San Rafael", "Buenavista", "Cote", "Katira"],
  Heredia: ["Heredia", "Mercedes", "San Francisco", "Ulloa", "Varablanca"],
  Hojaancha: ["Hojaancha", "Monte Romo", "Puerto Carrillo", "Huacas", "Matambú"],
  Jiménez: ["San Isidro", "Concepción", "San José", "San Juan", "Carolina"],
  "La Cruz": ["La Cruz", "Santa Cecilia", "La Garita", "Santa Elena"],
  Liberia: ["Liberia", "Cañas Dulces", "Mayorga", "Nacascolo", "Curubandé"],
  Limón: ["Limón", "Valle La Estrella", "Río Blanco", "Matama", "Guápiles"],
  "Los Chiles": ["Los Chiles", "Caño Negro", "El Amparo", "San Jorge"],
  "Mata Redonda": ["Santa Ana", "Salitral", "Pozos", "Uruca", "Piedades"],
  "Montes de Oca": ["San Pedro", "Sabanilla", "Mercedes", "San Rafael"],
  "Montes de Oro": ["Miramar", "La Unión", "San Isidro"],
  Mora: ["Ciudad Colón", "Guayabo", "Tabarcia", "Piedras Negras"],
  Moravia: ["San Vicente", "San Jerónimo", "La Trinidad"],
  Nandayure: ["Carmona", "Santa Rita", "Zapotal", "San Pablo", "Porvenir"],
  Naranjo: ["Naranjo", "San Miguel", "San José", "Cirrí Sur", "San Jerónimo"],
  Nicoya: ["Nicoya", "Mansión", "San Antonio", "Quebrada Honda", "Sámara"],
  Oreamuno: ["San Rafael", "Cot", "Potrero Cerrado", "Cipreses"],
  Orotina: ["Orotina", "El Mastate", "Coyolar", "La Ceiba"],
  Osa: ["Ciudad Cortés", "Palmar", "Sierpe", "Bahía Ballena", "Piedras Blancas"],
  Palmares: ["Palmares", "Zaragoza", "Buenos Aires", "Santiago", "Candelaria"],
  Parrita: ["Parrita"],
  "Pérez Zeledón": ["San Isidro de El General", "General", "Daniel Flores", "Rivas", "San Pedro"],
  Poás: ["San Pedro", "San Juan", "San Rafael", "Carrillos", "Sabana Redonda"],
  Puntarenas: ["Puntarenas", "Pitahaya", "Chomes", "Lepanto", "Paquera"],
  Puriscal: ["Santiago", "Mercedes Sur", "Barbacoas", "Grifo Alto", "San Rafael"],
  "San Carlos": ["Quesada", "Florencia", "Buenavista", "Aguas Zarcas", "Venecia"],
  "San José": ["San José", "Catedral", "Zapote", "San Francisco", "Hospital"],
  "San Mateo": ["San Mateo", "Desmonte", "Jesús María"],
  "San Pablo": ["San Pablo", "San Rafael", "San Pedro"],
  "San Ramón": ["San Ramón", "Santiago", "San Juan", "Piedades Norte", "Piedades Sur"],
  "Santa Ana": ["Santa Ana", "Salitral", "Pozos", "Uruca", "Piedades"],
  "Santa Bárbara": ["Santa Bárbara", "San Pedro"],
  "Santa Cruz": ["Santa Cruz", "Bolsón", "Veintisiete de Abril", "Tempate", "Cartagena"],
  "Santa María": ["Santa María", "Santa Rosa", "Santa Cruz"],
  "Santo Domingo": ["Santo Domingo", "San Vicente", "San Miguel", "Paracito", "Santo Tomás"],
  Sarapiquí: ["Puerto Viejo", "La Virgen", "Horquetas", "Llanuras del Gaspar", "Cureña"],
  Siquirres: ["Siquirres", "Pacuarito", "Florida", "Germania", "Cairo"],
  Talamanca: ["Bribri", "Bratsi", "Sixaola", "Cahuita"],
  Tarrazú: ["San Marcos", "San Lorenzo", "San Carlos"],
  Tibás: ["San Juan", "Cinco Esquinas", "Anselmo Llorente", "León XIII", "Colima"],
  Tilarán: ["Tilarán", "Quebrada Grande", "Tronadora", "La Cruz", "Santa Rosa"],
  Turrialba: ["Turrialba", "La Suiza", "Peralta", "Santa Teresita", "Pavones"],
  Turrubares: ["San Pablo", "San Pedro", "San Juan de Mata", "San Luis"],
  Upala: ["Upala", "Aguas Claras", "San José", "Bijagua"],
  "Valverde Vega": ["Sarchí Norte", "Sarchí Sur", "Toro Amarillo", "San Pedro", "Rodríguez"],
  "Vázquez de Coronado": ["San Isidro", "San Rafael", "Dulce Nombre de Jesús", "Patalillo", "Cascajal"],
};
